# Generated by Django 4.2.2 on 2023-06-28 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aviary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("condition", models.CharField(max_length=256)),
                ("last_ward_round", models.DateField()),
            ],
        ),
    ]
