# Generated by Django 4.2.2 on 2023-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aviary",
            options={"verbose_name": "Voliere", "verbose_name_plural": "Volieren"},
        ),
        migrations.AlterField(
            model_name="aviary",
            name="condition",
            field=models.CharField(max_length=256, verbose_name="Zustand"),
        ),
        migrations.AlterField(
            model_name="aviary",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="aviary",
            name="last_ward_round",
            field=models.DateField(verbose_name="letzte Visite"),
        ),
    ]
