# Generated by Django 4.2.7 on 2024-02-05 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailadress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Emailadresse',
                'verbose_name_plural': 'Emailadressen',
            },
        ),
        migrations.CreateModel(
            name='BirdEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.bird', verbose_name='Vogel')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendemail.emailadress', verbose_name='Emailadresse')),
            ],
            options={
                'verbose_name': 'Vogel-Email',
                'verbose_name_plural': 'Vogel-Emails',
            },
        ),
    ]
