# Generated by Django 5.2.4 on 2025-07-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0009_merge_20250609_2033'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatisticGroup',
            new_name='StatisticIndividual',
        ),
        migrations.AlterModelOptions(
            name='statisticconfiguration',
            options={'verbose_name': 'Statistik-Konfiguration', 'verbose_name_plural': 'Statistik-Konfiguration'},
        ),
        migrations.AlterModelOptions(
            name='statisticindividual',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Statistik-Individuum', 'verbose_name_plural': 'Statistik-Individuen'},
        ),
        migrations.RemoveField(
            model_name='statisticconfiguration',
            name='name',
        ),
        migrations.AddField(
            model_name='statisticconfiguration',
            name='show_total_patients',
            field=models.BooleanField(default=True, help_text='Zeigt die Gesamtanzahl aller Patienten seit Beginn der Aufzeichnungen', verbose_name='Gesamtanzahl aller Patienten anzeigen'),
        ),
        migrations.AddField(
            model_name='statisticconfiguration',
            name='show_year_total_patients',
            field=models.BooleanField(default=True, help_text='Zeigt die Gesamtanzahl aller aufgenommenen Patienten des aktuellen Jahres', verbose_name='Gesamtanzahl Patienten dieses Jahr anzeigen'),
        ),
        migrations.CreateModel(
            name='StatisticTotalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Gruppe für die Gesamtstatistik', max_length=100, verbose_name='Gruppenname')),
                ('color', models.CharField(default='#28a745', help_text='Hex-Farbcode für die Anzeige', max_length=7, verbose_name='Farbe')),
                ('order', models.PositiveIntegerField(default=0, help_text='Bestimmt die Reihenfolge der Karten in der Gesamtübersicht', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, help_text='Soll diese Gruppe in der Gesamtstatistik angezeigt werden?', verbose_name='Aktiv')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('status_list', models.ManyToManyField(help_text='Welche Status gehören zu dieser Gesamtgruppe?', to='bird.birdstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Statistik-Insgesamt Gruppe',
                'verbose_name_plural': 'Statistik-Insgesamt',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StatisticYearGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Gruppe für die Jahresstatistik', max_length=100, verbose_name='Gruppenname')),
                ('color', models.CharField(default='#007bff', help_text='Hex-Farbcode für die Anzeige', max_length=7, verbose_name='Farbe')),
                ('order', models.PositiveIntegerField(default=0, help_text='Bestimmt die Reihenfolge der Karten in der Jahresübersicht', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, help_text='Soll diese Gruppe in der Jahresstatistik angezeigt werden?', verbose_name='Aktiv')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('status_list', models.ManyToManyField(help_text='Welche Status gehören zu dieser Jahresgruppe?', to='bird.birdstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Statistik-Jahr Gruppe',
                'verbose_name_plural': 'Statistik-Jahr',
                'ordering': ['order', 'name'],
            },
        ),
    ]
