# Generated by Django 4.2.4 on 2023-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bird',
            options={'ordering': ['name'], 'verbose_name': 'Vogel', 'verbose_name_plural': 'Vögel'},
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='age',
            field=models.CharField(choices=[('unbekannt', 'unbekannt'), ('Ei', 'Ei'), ('Nestling', 'Nestling'), ('Ästling', 'Ästling'), ('Juvenil', 'Juvenil'), ('Adult', 'Adult')], max_length=15, verbose_name='Alter'),
        ),
    ]
