# Generated by Django 4.2.6 on 2023-10-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallenbird',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung'),
        ),
    ]
