# Generated by Django 4.2.3 on 2023-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallenbird',
            name='costs',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Kosten'),
        ),
    ]
