# Generated by Django 4.2.6 on 2023-10-08 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdstatus',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Erläuterungen'),
        ),
    ]
