# Generated by Django 4.2.3 on 2023-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="birdstatus",
            name="description",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="circumstance",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="fallenbird",
            name="costs",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
