# Generated by Django 5.2.2 on 2025-06-07 13:33

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0002_aviary_capacity_aviary_contact_email_and_more'),
        ('bird', '0002_add_name_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='age_group',
            field=models.CharField(blank=True, choices=[('unbekannt', 'unbekannt'), ('Ei', 'Ei'), ('Nestling', 'Nestling'), ('Ästling', 'Ästling'), ('Juvenil', 'Juvenil'), ('Adult', 'Adult')], max_length=15, null=True, verbose_name='Alter'),
        ),
        migrations.AddField(
            model_name='bird',
            name='aviary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aviary.aviary', verbose_name='Voliere'),
        ),
        migrations.AddField(
            model_name='bird',
            name='circumstance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bird.circumstance', verbose_name='Fundumstände'),
        ),
        migrations.AddField(
            model_name='bird',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AddField(
            model_name='bird',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='bird',
            name='finder_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Finder Email'),
        ),
        migrations.AddField(
            model_name='bird',
            name='finder_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Finder Name'),
        ),
        migrations.AddField(
            model_name='bird',
            name='finder_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finder Telefon'),
        ),
        migrations.AddField(
            model_name='bird',
            name='found_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum des Fundes'),
        ),
        migrations.AddField(
            model_name='bird',
            name='found_location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Fundort'),
        ),
        migrations.AddField(
            model_name='bird',
            name='gender',
            field=models.CharField(blank=True, choices=[('Weiblich', 'Weiblich'), ('Männlich', 'Männlich'), ('Unbekannt', 'Unbekannt')], max_length=15, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='bird',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='bird',
            name='species',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Art'),
        ),
        migrations.AddField(
            model_name='bird',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bird.birdstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bird',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
        migrations.AddField(
            model_name='bird',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gewicht'),
        ),
        migrations.AddField(
            model_name='bird',
            name='wing_span',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Flügelspannweite'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Erläuterungen'),
        ),
    ]
