# Generated by Django 4.2.4 on 2023-08-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0002_alter_bird_options_alter_fallenbird_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallenbird',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
