# Generated by Django 4.2.4 on 2023-08-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_fallenbird_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallenbird',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung'),
        ),
    ]
