# Generated by Django 5.2.2 on 2025-06-07 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_expand_bird_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fallenbird',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Todesursache'),
        ),
        migrations.AddField(
            model_name='fallenbird',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallen_birds_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='fallenbird',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Todesdatum'),
        ),
        migrations.AddField(
            model_name='fallenbird',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
    ]
