# Generated by Django 5.2.2 on 2025-06-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0004_expand_costs_model'),
    ]

    operations = [
    ]
