# Generated by Django 4.2.5 on 2023-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bird", "0004_alter_fallenbird_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bird",
            name="description",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Beschreibung"
            ),
        ),
    ]
