# Generated by Django 5.2.2 on 2025-06-07 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0005_auto_20250607_1837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallenbird',
            options={'verbose_name': 'Gefallener Vogel', 'verbose_name_plural': 'Gefallene Vögel'},
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='age',
            field=models.CharField(blank=True, choices=[('unbekannt', 'unbekannt'), ('Ei', 'Ei'), ('Nestling', 'Nestling'), ('Ästling', 'Ästling'), ('Juvenil', 'Juvenil'), ('Adult', 'Adult')], max_length=15, null=True, verbose_name='Alter'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='bird_identifier',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Patienten Alias'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='date_found',
            field=models.DateField(blank=True, null=True, verbose_name='Datum des Fundes'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='diagnostic_finding',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Diagnose bei Fund'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='find_circumstances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bird.circumstance', verbose_name='Fundumstände'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='place',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ort des Fundes'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='sex',
            field=models.CharField(blank=True, choices=[('Weiblich', 'Weiblich'), ('Männlich', 'Männlich'), ('Unbekannt', 'Unbekannt')], max_length=15, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bird.birdstatus'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallen_birds_handled', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
