# Generated by Django 5.2.2 on 2025-06-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0006_alter_fallenbird_options_alter_fallenbird_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallenbird',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bird.birdstatus', verbose_name='Status'),
        ),
    ]
