# Generated by Django 5.2.2 on 2025-06-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0007_alter_fallenbird_status'),
        ('bird', '0008_set_default_notification_settings'),
    ]

    operations = [
    ]
