# Generated by Django 5.2.4 on 2025-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0009_merge_20250609_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallenbird',
            name='patient_file_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Patientenakte geschlossen am'),
        ),
        migrations.AddField(
            model_name='fallenbird',
            name='release_location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Auswilderungsort'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='sent_to',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Übermittelt nach'),
        ),
    ]
