# Generated by Django 5.2.4 on 2025-07-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0010_fallenbird_patient_file_close_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallenbird',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patienten'},
        ),
    ]
