# Generated by Django 5.2.7 on 2025-10-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0011_alter_fallenbird_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regionen',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='fallenbird',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Automatisch erkannte oder manuell gewählte Region / Stadt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallen_birds', to='bird.birdregion', verbose_name='Region'),
        ),
    ]
