# Generated by Django 5.2.7 on 2025-10-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0014_regionbackfilltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildvogelhilfeCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Adresse Beschreibung')),
                ('latitude', models.FloatField(verbose_name='Breitengrad')),
                ('longitude', models.FloatField(verbose_name='Längengrad')),
            ],
            options={
                'verbose_name': 'Wildvogelhilfe Standort',
                'verbose_name_plural': 'Wildvogelhilfe Standorte',
            },
        ),
        migrations.AlterField(
            model_name='birdregion',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Wird automatisch aus dem Namen erzeugt.', max_length=160, unique=True, verbose_name='URL-Kürzel'),
        ),
    ]
