# Generated by Django 5.2.2 on 2025-06-07 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Kapazität'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='contact_person',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ansprechpartner'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='current_occupancy',
            field=models.PositiveIntegerField(default=0, verbose_name='Aktuelle Belegung'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='aviary',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='condition',
            field=models.CharField(blank=True, choices=[('Offen', 'Offen'), ('Geschlossen', 'Geschlossen'), ('Gesperrt', 'Gesperrt')], max_length=256, null=True, verbose_name='Zustand'),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aviary',
            name='last_ward_round',
            field=models.DateField(blank=True, null=True, verbose_name='letzte Visite'),
        ),
    ]
