# Generated by Django 4.2.3 on 2023-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviary', '0003_alter_aviary_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviary',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Bemerkungen'),
        ),
    ]
