# Generated by Django 5.2.2 on 2025-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_options_contact_city_contact_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postleitzahl'),
        ),
    ]
