# Generated by Django 4.2.4 on 2023-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescuer',
            options={'ordering': ['last_name'], 'verbose_name': 'Finder', 'verbose_name_plural': 'Finder'},
        ),
    ]
