# Generated by Django 4.2.3 on 2023-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rescuer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rescuer",
            options={"verbose_name": "Finder", "verbose_name_plural": "Finder"},
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="city",
            field=models.CharField(max_length=200, verbose_name="Stadt"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="first_name",
            field=models.CharField(max_length=200, verbose_name="Vorname"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="Nachname"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="phone",
            field=models.CharField(max_length=200, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="street",
            field=models.CharField(max_length=200, verbose_name="Straße"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="street_number",
            field=models.CharField(max_length=20, verbose_name="Nummer"),
        ),
        migrations.AlterField(
            model_name="rescuer",
            name="zip_code",
            field=models.CharField(max_length=200, verbose_name="PLZ"),
        ),
    ]
