# Generated by Django 5.2.6 on 2025-09-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WildbirdHelpStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "officially_authorised",
                    models.BooleanField(
                        default=False,
                        help_text="Markiert Stationen mit amtlicher Anerkennung.",
                        verbose_name="Amtlich anerkannt",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Administratives Feld; wird nicht öffentlich angezeigt.",
                        verbose_name="Interne Notiz",
                    ),
                ),
                (
                    "checked_until",
                    models.DateField(
                        blank=True,
                        help_text="Datum der letzten Überprüfung der Stationsdaten.",
                        null=True,
                        verbose_name="Geprüft bis",
                    ),
                ),
                (
                    "approved_for_publication",
                    models.BooleanField(
                        default=True,
                        help_text="Nur freigegebene Stationen erscheinen auf der öffentlichen Karte.",
                        verbose_name="Für Karte freigeben",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Spezialisierung"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Freitextadresse als Fallback für Darstellungen.",
                        max_length=255,
                        verbose_name="Adresse",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="Telefon"),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        help_text="Optional.",
                        max_length=64,
                        verbose_name="Telefon (alternativ)",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Ansprechperson"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postleitzahl"
                    ),
                ),
                (
                    "postal_code_prefix",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="PLZ-Region"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=128, verbose_name="Ort"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=255, verbose_name="Straße"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=128, verbose_name="Region"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Bundesland/Kanton"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Deutschland",
                        max_length=128,
                        verbose_name="Land",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Längengrad",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Freitext-Hinweise, die im Karten-Popup angezeigt werden.",
                        verbose_name="Öffentliche Hinweise",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="aktiv",
                        help_text="Z. B. aktiv, inaktiv oder NABU.",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Wildvogelhilfe-Station",
                "verbose_name_plural": "Wildvogelhilfe-Stationen",
                "ordering": ("name",),
                "unique_together": {("name", "city", "country")},
            },
        ),
    ]
