# Generated by Django 5.2.6 on 2025-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wildbirdhelpstation",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Freitextadresse oder zusätzliche Anfahrtsinformationen.",
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="wildbirdhelpstation",
            name="postal_code_prefix",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="PLZ-Region"
            ),
        ),
        migrations.AlterField(
            model_name="wildbirdhelpstation",
            name="specialization",
            field=models.TextField(
                blank=True,
                help_text="Ausführliche Beschreibung der aufgenommenen Tierarten.",
                verbose_name="Spezialisierung",
            ),
        ),
    ]
