# Generated by Django 5.2.6 on 2025-09-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_alter_wildbirdhelpstation_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StationReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional: erhält E-Mails, wenn neue Vorschläge eingehen.",
                        max_length=254,
                        verbose_name="Benachrichtigungsadresse",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
            ],
            options={
                "verbose_name": "Stationsvorschlag-Einstellungen",
                "verbose_name_plural": "Stationsvorschlag-Einstellungen",
            },
        ),
        migrations.CreateModel(
            name="StationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Stationsname")),
                (
                    "specialization",
                    models.TextField(blank=True, verbose_name="Spezialisierung"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Freitext für zusätzliche Hinweise.",
                        verbose_name="Beschreibung",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postleitzahl"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=128, verbose_name="Ort"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Bundesland/Kanton"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Deutschland",
                        max_length=128,
                        verbose_name="Land",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breitengrad",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Längengrad",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="Telefon"),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="Öffentliche Hinweise"),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Kontaktname"
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Kontakt E-Mail"
                    ),
                ),
                (
                    "reporter_phone",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Kontakt Telefon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("approved", "Übernommen"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bearbeitet am"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eingereicht am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="station_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bearbeitet von",
                    ),
                ),
                (
                    "related_station",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wird gesetzt, wenn der Vorschlag übernommen wurde.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stations.wildbirdhelpstation",
                        verbose_name="Verknüpfte Station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stationsvorschlag",
                "verbose_name_plural": "Stationsvorschläge",
                "ordering": ("-created_at",),
            },
        ),
    ]
