# Generated by Django 5.2.6 on 2025-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_stationreportsettings_stationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationreport',
            name='address',
            field=models.TextField(blank=True, verbose_name='Anfahrtsinformationen'),
        ),
        migrations.AlterField(
            model_name='wildbirdhelpstation',
            name='address',
            field=models.TextField(blank=True, help_text='Freitext für Wegbeschreibungen oder zusätzliche Hinweise.', verbose_name='Anfahrtsinformationen'),
        ),
    ]
