# Generated by Django 5.2.7 on 2025-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_stationreport_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_header_note', models.BooleanField(default=True, help_text='Schaltet den gelben Hinweisblock direkt unter der Überschrift ein.', verbose_name='Hinweis im Kopf anzeigen')),
                ('header_note_text', models.TextField(blank=True, help_text='Inhalt für den oberen Hinweisblock. Unterstützt einfachen Text/HTML.', verbose_name='Text Kopf-Hinweis')),
                ('show_info_note', models.BooleanField(default=True, help_text='Steuert den Hinweisblock im Informationsbereich unter der Karte.', verbose_name='Hinweis im Infopanel anzeigen')),
                ('info_note_text', models.TextField(blank=True, help_text='Inhalt für den Hinweisblock im Infopanel. Unterstützt einfachen Text/HTML.', verbose_name='Text Infopanel-Hinweis')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Stations Einstellungen',
                'verbose_name_plural': 'Stations Einstellungen',
            },
        ),
    ]
