# Generated by Django 5.2.7 on 2025-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_stationmapsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationmapsettings',
            name='page_title',
            field=models.CharField(blank=True, help_text="Überschrift der Karten-Seite. Leer = Standard '🦅 Wildvogelhilfen – Interaktive Karte'.", max_length=120, verbose_name='Seitentitel'),
        ),
    ]
