# Generated by Django 5.2.3 on 2025-06-10 11:14

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung für diese Notiz', max_length=200, verbose_name='Name der Notiz')),
                ('inhalt', django_ckeditor_5.fields.CKEditor5Field(help_text='Inhalt der Notiz in Markdown-Format', verbose_name='Inhalt')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['-geaendert_am'],
            },
        ),
    ]
