# Generated by Django 5.2.3 on 2025-06-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiz',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID des verknüpften Objekts (unterstützt sowohl Integer als auch UUID)', max_length=255, null=True, verbose_name='Objekt ID'),
        ),
    ]
