# Generated by Django 5.2.3 on 2025-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizen', '0002_alter_notiz_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Eindeutige Kennung für diese Seite', max_length=100, unique=True, verbose_name='Seiten-Identifier')),
                ('name', models.CharField(help_text='Anzeigename für diese Seite', max_length=200, verbose_name='Seitenname')),
                ('description', models.TextField(blank=True, help_text='Beschreibung der Seite', null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Seite',
                'verbose_name_plural': 'Seiten',
                'ordering': ['name'],
            },
        ),
    ]
