# Generated by Codex on 2025-09-22

import uuid
from django.db import migrations, models


def generate_public_tokens(apps, schema_editor):
    Notiz = apps.get_model('notizen', 'Notiz')
    for notiz in Notiz.objects.all():
        notiz.public_token = uuid.uuid4()
        notiz.save(update_fields=['public_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('notizen', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiz',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text='Ermöglicht den Zugriff über einen öffentlichen Link ohne Anmeldung.',
                verbose_name='Öffentlich zugänglich'
            ),
        ),
        migrations.AddField(
            model_name='notiz',
            name='public_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                verbose_name='Öffentlicher Zugriffstoken'
            ),
        ),
        migrations.RunPython(generate_public_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='notiz',
            name='public_token',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name='Öffentlicher Zugriffstoken'
            ),
        ),
    ]
