# Generated by Django 5.2.2 on 2025-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlog',
            old_name='included_jagdbehoerde',
            new_name='include_jagdbehörde',
        ),
        migrations.RenameField(
            model_name='reportlog',
            old_name='included_naturschutzbehoerde',
            new_name='include_naturschutzbehörde',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='bird_count',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='report_type',
        ),
        migrations.AddField(
            model_name='reportlog',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/csv/', verbose_name='CSV-Datei'),
        ),
        migrations.AddField(
            model_name='reportlog',
            name='email_sent_to',
            field=models.JSONField(blank=True, default=list, help_text='Liste der E-Mail-Adressen, an die der Report gesendet wurde', verbose_name='E-Mail gesendet an'),
        ),
        migrations.AddField(
            model_name='reportlog',
            name='patient_count',
            field=models.IntegerField(default=0, verbose_name='Anzahl Patienten'),
        ),
    ]
