# Generated by Django 5.2.4 on 2025-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_included_jagdbehoerde_reportlog_include_jagdbehörde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticreport',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('biannually', 'Halbjährlich'), ('annually', 'Jährlich')], default='monthly', max_length=20, verbose_name='Häufigkeit'),
        ),
    ]
