# Generated by Django 5.2.4 on 2025-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_automaticreport_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticreport',
            name='include_aviary',
            field=models.BooleanField(default=False, help_text='Voliere-Zuordnung in den Bericht einschließen', verbose_name='Voliere'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_bird_species',
            field=models.BooleanField(default=True, help_text='Vogelart in den Bericht einschließen', verbose_name='Vogelart'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_bird_status',
            field=models.BooleanField(default=True, help_text='Status des Vogels in den Bericht einschließen', verbose_name='Vogelstatus'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_circumstances',
            field=models.BooleanField(default=True, help_text='Fundumstände in den Bericht einschließen', verbose_name='Fundumstände'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_date_found',
            field=models.BooleanField(default=True, help_text='Datum des Vogelfunds in den Bericht einschließen', verbose_name='Funddatum'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_finder_info',
            field=models.BooleanField(default=False, help_text='Informationen zum Finder in den Bericht einschließen', verbose_name='Finder-Informationen'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_location',
            field=models.BooleanField(default=True, help_text='Fundort in den Bericht einschließen', verbose_name='Fundort'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_notes',
            field=models.BooleanField(default=False, help_text='Notizen zum Vogel in den Bericht einschließen', verbose_name='Notizen'),
        ),
    ]
