# Generated by Django 5.2.4 on 2025-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_automaticreport_include_aviary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticreport',
            name='include_notes',
            field=models.BooleanField(default=False, help_text='Bemerkungen zum Vogel in den Bericht einschließen', verbose_name='Bemerkungen'),
        ),
    ]
