# Generated by Django 5.2.4 on 2025-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_automaticreport_include_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticreport',
            name='include_close_date',
            field=models.BooleanField(default=False, help_text='Datum der Aktenschließung in den Bericht einschließen', verbose_name='Schließungsdatum'),
        ),
        migrations.AddField(
            model_name='automaticreport',
            name='include_release_location',
            field=models.BooleanField(default=False, help_text='Auswilderungsort in den Bericht einschließen', verbose_name='Auswilderungsort'),
        ),
    ]
