# Generated by Django 5.2.4 on 2025-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_automaticreport_include_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticreport',
            name='include_sent_to',
            field=models.BooleanField(default=False, help_text='Information über Übermittlung in den Bericht einschließen', verbose_name='Übermittelt nach'),
        ),
    ]
