# Generated by Django 4.2.3 on 2023-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='costs',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='created',
            field=models.DateField(verbose_name='Gebucht am'),
        ),
    ]
