# Generated by Django 5.2.2 on 2025-06-07 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0004_expand_costs_model'),
        ('costs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Betrag'),
        ),
        migrations.AddField(
            model_name='costs',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='bird.bird', verbose_name='Vogel'),
        ),
        migrations.AddField(
            model_name='costs',
            name='category',
            field=models.CharField(choices=[('medical', 'Medizinisch'), ('food', 'Nahrung'), ('equipment', 'Ausrüstung'), ('transport', 'Transport'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='costs',
            name='cost_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kostendatum'),
        ),
        migrations.AddField(
            model_name='costs',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='costs',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='costs',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AddField(
            model_name='costs',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='costs',
            name='vendor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Anbieter'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='costs',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Betrag (legacy)'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='id_bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='bird.fallenbird', verbose_name='Patient'),
        ),
    ]
