# Generated by Django 5.2.2 on 2025-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_expand_costs_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Gebucht am'),
        ),
    ]
